#!/usr/bin/env bash
#scp

if [ $# -eq 4 ]
then
    scp -i "$4" "$1" "$3@$2:~/"
elif [ $# -eq 3 ]
then
    scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
else
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
