#!/usr/bin/env bash
#script install and config my web server (nginx) and change redirectme

sudo apt install -y nginx
echo "Hello World!" > /var/www/html/index.html
replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/youtu.be\/pildU9lK6vM permanent;"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default
sudo service nginx restart
