#!/usr/bin/env bash
#install load balancer
sudo apt update -y
sudo apt install -y haproxy
arg="\nfrontend app \n\tbind *:80\n\tdefault_backend apps\nbackend apps\n\tbalance roundrobin\n\tserver 511048-web-01 52.1.156.177:80 check\n\tserver 511048-web-02 54.167.183.43:80 check\n"
sudo printf "%s""$arg">>/etc/haproxy/haproxy.cfg
sudo printf "ENABLED=1">>/etc/default/haproxy
sudo service haproxy restart
