#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes
i=0
j=1
hours=0
while ((i < 13))
do
	echo "Hour: $hours"
	j=1
	while ((j < 60))
	do
		echo "$j"
		((j++))
	done
	((hours++))
	((i++))
done