#!/usr/bin/env bash
#script that displays all active IPv4 IPs on the machine it’s executed on
#using regex : "ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 6-"
ifconfig -a | grep "inet " | awk '{print $2}'